config/routes.rb
VinoSocialis::Application.routes.draw do

  scope "/(:locale)", :locale => /fr|en/ do
    
    resources :wine_racks do
      member do
        get 'place'
        get 'apply_place'
        post 'empty'
      end
    end

    resources :consumptions
    
    resources :pairings do
      collection do
        get 'search'
      end
    end
    
    resources :bottles do
      member do
        get 'consume'
        get 'place'
        get 'unplace'
      end
      collection do
        get 'not_placed'
      end
    end
      
    resources :tastings
    
    resources :estates do
      member do
        post 'validate'
        post 'unvalidate'
        get 'replace'
        post 'comment'
      end
    end

    resources :wines do
      member do
        post 'validate'
        post 'unvalidate'
        get 'taste'
        get 'tastings'
        get 'encave'
        get 'replace'
        get 'add_label'
        post 'comment'
      end
      collection do
        get 'recommanded'
      end
    end

    resources :wine_colors

    resources :countries do
      member do
        post 'comment'
      end
    end
    resources :regions do
      member do
        post 'comment'
      end
    end
    resources :areas do
      member do
        post 'comment'
      end
    end
    resources :superficies
    resources :volumes
    resources :color_volumes
    resources :area_color_grapes
    
    resources :grape_varieties do
      member do
        post 'validate'
        get 'replace'
        post 'do_replace'
      end
    end
  
    devise_for :users
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'stat'
        get 'dashboard'
        get 'become'
        get 'tags'
        get 'tastings'
        get 'books'
        get 'follow'
        get 'unfollow'
        get 'friends'
      end
    end
    
    resources :conversations do
      collection do
        get 'admins'
        get 'bug'
        delete 'destroy_multiple'
      end
    end
    
    resources :glossaries
    
    resources :moderations do
      collection do
        get 'sheets'
        get 'labels'
        get 'books'
        get 'clean'
        get 'proposals'
      end
    end
    
    resources :wines_and_estates do
      collection do
        get 'search'
      end
    end
    
    resources :labels do
      member do
        post 'validate'
      end
    end
    
    resources :vintages do
      collection do
        post 'rate'
      end
    end
    
    resources :proposals do
      member do
        post 'close'
      end
    end
    
    resources :books do
      member do
        post 'validate'
        get 'own'
        post 'comment'
      end
    end
    resources :book_ratings
    
    root :to => "home#index"

    match '/why', :to => "home#why"
    match '/about', :to => "home#about"
    match '/discover', :to => "home#discover"
    match '/temperature', :to => "home#temperature"
    match '/track', :to => "home#track"
    match '/share', :to => "home#share"
    match '/newcomer', :to => "home#newcomer"
    match '/sitemap', :to => "home#sitemap"
  end

  match '', :to => redirect { |p, r| p[:locale] ? "/#{p[:locale]}/" : '/fr/' }
  
  match '/areas/for_region_id/:region_id' => 'areas#for_region_id'
  
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
end

app/models/moderation.rb
class Moderation < ActiveRecord::Base
end

app/controllers/moderations_controller.rb
class ModerationsController < ApplicationController
  
  authorize_resource
  
  def sheets
    @grape_varieties = GrapeVariety.not_validated
    @estates = Estate.not_validated
    @wines = Wine.not_validated
  end
  
  def labels
    @labels = Label.not_validated
  end
  
  def books
    @books = Book.not_validated
  end
  
  def clean
    @wines = Wine.unscoped.where('validation = ? AND created_at < ?', false, Date.current().months_ago(1)).select(&:destroyable?)
    @estates = Estate.unscoped.where('validation = ? AND created_at < ?', false, Date.current().months_ago(1)).select(&:destroyable?)
  end
  
  def proposals
    @proposals = Proposal.opened
  end
end

app/views/moderations/_book.html.erb
<tr>
  <td style="text-align:center;vertical-align:middle;"><%= link_to book.title, book %></td>
  <td style="text-align:center;vertical-align:middle;"><%= book.authors %></td>
  <td style="text-align:center;vertical-align:middle;"><%= book.user.name %></td>
  <td style="text-align:center;vertical-align:middle;"><%= link_to_edit edit_book_path(book) %></td>
  <td style="text-align:center;vertical-align:middle;"><%= link_to_destroy book %></td>
  <td style="text-align:center;vertical-align:middle;"><%= link_to_validate validate_book_path(book) %></td>
</tr>

app/views/moderations/_estate.html.erb
<tr>
  <td><%= estate.name %></td>
  <td><%= estate.town %> (<%= estate.country %>)</td>
  <td><%= link_to estate.www, estate.www %></td>
  <td><%= estate.user.name %></td>
  <td><%= link_to_edit edit_estate_path(estate) %></td>
  <td><%= link_to_validate validate_estate_path(estate) %></td>
  <td><%= content_tag(:a, content_tag(:i, "", class: "icon-refresh") + ' Remplacer', :href => wines_and_estates_path(replaced_estate: estate.id)) %></td>
</tr>

app/views/moderations/_grape_variety.html.erb
<tr>
  <td><%= link_to grape_variety.name, grape_variety %></td>
  <td><%= grape_variety.wines.size %></td>
  <td><%= link_to_edit edit_grape_variety_path(grape_variety) %></td>
  <td><%= link_to_destroy grape_variety if grape_variety.wines.empty? %></td>
  <td><%= link_to_validate validate_grape_variety_path(grape_variety) %></td>
  <td><%= content_tag(:a, content_tag(:i, "", class: "icon-refresh") + ' Remplacer', :href => replace_grape_variety_path(grape_variety)) %></td>
</tr>

app/views/moderations/_label.html.erb
<tr>
  <td style="text-align:center;vertical-align:middle;"><%= image_tag label.image_url(:big).to_s %></td>
  <td style="text-align:center;vertical-align:middle;">
    <%= link_to wine_name(label.wine, estate: true), label.wine %>
    <% if label.wine.labels.validated.any? %>
      <br />
      <% label.wine.labels.validated.each do |l| %>
        <%= image_tag l.image_url(:mini).to_s %>
      <% end %>
    <% end %>
  </td>
  <td style="text-align:center;vertical-align:middle;"><%= label.user.name %></td>
  <td style="text-align:center;vertical-align:middle;"><%= link_to_destroy label %></td>
  <td style="text-align:center;vertical-align:middle;"><%= link_to_validate validate_label_path(label) %></td>
</tr>

app/views/moderations/_proposal.html.erb
<tr>
  <td><%= link_to proposal.page, proposal.page %></td>
  <td><%= link_to proposal.user.name, proposal.user %></td>
  <td><%= link_to "Proposition ##{proposal.id}", proposal %></td>
</tr>

app/views/moderations/_wine.html.erb
<tr>
  <td><%= link_to wine.estate.name, wine.estate %></td>
  <td><%= link_to wine.name, wine %></td>
  <td><%= wine.area.name %></td>
  <td><%= wine_icon wine %></td>
  <td><%= wine.user.name %></td>
  <td><%= link_to_edit edit_wine_path(wine) %></td>
  <td><%= link_to_validate validate_wine_path(wine) %></td>
  <td><%= content_tag(:a, content_tag(:i, "", class: "icon-refresh") + ' Remplacer', :href => wines_and_estates_path(replaced_wine: wine.id)) %></td>
</tr>

app/views/moderations/books.html.erb
<% if @books.any? %>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th style="text-align:center;vertical-align:middle;">Titre</th>
        <th style="text-align:center;vertical-align:middle;">Auteur</th>
        <th style="text-align:center;vertical-align:middle;">Utilisateur</th>
        <th style="text-align:center;vertical-align:middle;">Editer</th>
        <th style="text-align:center;vertical-align:middle;">Suppression</th>
        <th style="text-align:center;vertical-align:middle;">Validation</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @books, :partial => 'book' %>
    </tbody>
  </table>
<% end %>

app/views/moderations/clean.html.erb
<div class="white-opacity rounded">
  <h2>Vins</h2>
  <table class="table table-condensed">
    <% @wines.each do |wine| %>
    <tr>
      <td><%= link_to wine.estate.name, wine.estate %></td>
      <td><%= link_to wine.name, wine %></td>
      <td><%= wine.area.name %></td>
      <td><%= wine_icon wine %></td>
      <td><%= wine.user.name %></td>
      <td><%= link_to_destroy wine %></td>
    </tr>
    <% end %>
  </table>
</div>

<br />
 
 <div class="white-opacity rounded">
  <h2>Producteurs</h2> 
  <table class="table table-condensed">
    <% @estates.each do |estate| %>
    <tr>
      <td><%= link_to estate.name, estate %></td>
      <td><%= estate.town %> (<%= estate.country %>)</td>
      <td><%= link_to estate.www, estate.www %></td>
      <td><%= estate.user.name %></td>
      <td><%= link_to_destroy(estate) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/moderations/labels.html.erb
<% if @labels.any? %>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th style="text-align:center;vertical-align:middle;">Etiquette</th>
        <th style="text-align:center;vertical-align:middle;">Vin correspondant</th>
        <th style="text-align:center;vertical-align:middle;">Suppression</th>
        <th style="text-align:center;vertical-align:middle;">Validation</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @labels, :partial => 'label' %>
    </tbody>
  </table>
<% end %>

app/views/moderations/proposals.html.erb
<% if @proposals.any? %>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th>Page</th>
        <th>Utilisateur</th>
        <th>Voir</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @proposals, :partial => 'proposal' %>
    </tbody>
  </table>
<% end %>

app/views/moderations/sheets.html.erb
<% if @grape_varieties.any? %>
  <h2><%= t('grape_variety.grape_varieties') %></h2>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th>Nom</th>
        <th>Vins correspondants</th>
        <th>Edition</th>
        <th>Suppression</th>
        <th>Validation</th>
        <th>Remplacement</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @grape_varieties, :partial => 'grape_variety' %>
    </tbody>
  </table>
  
  <br />
<% end %>
<% if @estates.any? %>
  <h2><%= t('estate.estates') %></h2>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th>Nom</th>
        <th>Ville (Pays)</th>
        <th>Site</th>
        <th>Fiche de</th>
        <th>Edition</th>
        <th>Validation</th>
        <th>Remplacement</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @estates, :partial => 'estate' %>
    </tbody>
  </table>
  
  <br />
<% end %>

<% if @wines.any? %>
  <h2><%= t('wine.wines') %></h2>
  <table class="table table-condensed white-opacity">
    <theader>
      <tr>
        <th>Producteur</th>
        <th>Nom</th>
        <th>Appellation</th>
        <th>Couleur</th>
        <th>Fiche de</th>
        <th>Edition</th>
        <th>Validation</th>
        <th>Remplacement</th>
      </tr>
    </theader>
    <tbody>
      <%= render :collection => @wines, :partial => 'wine' %>
    </tbody>
  </table>
<% end %>