config/routes.rb
VinoSocialis::Application.routes.draw do

  scope "/(:locale)", :locale => /fr|en/ do
    
    resources :wine_racks do
      member do
        get 'place'
        get 'apply_place'
        post 'empty'
      end
    end

    resources :consumptions
    
    resources :pairings do
      collection do
        get 'search'
      end
    end
    
    resources :bottles do
      member do
        get 'consume'
        get 'place'
        get 'unplace'
      end
      collection do
        get 'not_placed'
      end
    end
      
    resources :tastings
    
    resources :estates do
      member do
        post 'validate'
        post 'unvalidate'
        get 'replace'
        post 'comment'
      end
    end

    resources :wines do
      member do
        post 'validate'
        post 'unvalidate'
        get 'taste'
        get 'tastings'
        get 'encave'
        get 'replace'
        get 'add_label'
        post 'comment'
      end
      collection do
        get 'recommanded'
      end
    end

    resources :wine_colors

    resources :countries do
      member do
        post 'comment'
      end
    end
    resources :regions do
      member do
        post 'comment'
      end
    end
    resources :areas do
      member do
        post 'comment'
      end
    end
    resources :superficies
    resources :volumes
    resources :color_volumes
    resources :area_color_grapes
    
    resources :grape_varieties do
      member do
        post 'validate'
        get 'replace'
        post 'do_replace'
      end
    end
  
    devise_for :users
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'stat'
        get 'dashboard'
        get 'become'
        get 'tags'
        get 'tastings'
        get 'books'
        get 'follow'
        get 'unfollow'
        get 'friends'
      end
    end
    
    resources :conversations do
      collection do
        get 'admins'
        get 'bug'
        delete 'destroy_multiple'
      end
    end
    
    resources :glossaries
    
    resources :moderations do
      collection do
        get 'sheets'
        get 'labels'
        get 'books'
        get 'clean'
        get 'proposals'
      end
    end
    
    resources :wines_and_estates do
      collection do
        get 'search'
      end
    end
    
    resources :labels do
      member do
        post 'validate'
      end
    end
    
    resources :vintages do
      collection do
        post 'rate'
      end
    end
    
    resources :proposals do
      member do
        post 'close'
      end
    end
    
    resources :books do
      member do
        post 'validate'
        get 'own'
        post 'comment'
      end
    end
    resources :book_ratings
    
    root :to => "home#index"

    match '/why', :to => "home#why"
    match '/about', :to => "home#about"
    match '/discover', :to => "home#discover"
    match '/temperature', :to => "home#temperature"
    match '/track', :to => "home#track"
    match '/share', :to => "home#share"
    match '/newcomer', :to => "home#newcomer"
    match '/sitemap', :to => "home#sitemap"
  end

  match '', :to => redirect { |p, r| p[:locale] ? "/#{p[:locale]}/" : '/fr/' }
  
  match '/areas/for_region_id/:region_id' => 'areas#for_region_id'
  
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  
  load_resource
  
  def index
    @conversations = current_user.mailbox.inbox
  end
  
  def show
    @receipts = current_user.mailbox.receipts_for(@conversation).not_trash
    render :action => :show
    @receipts.mark_as_read
  end
  
  def new
    @users = params[:user].blank? ? [] : [User.find(params[:user])]
    @admin_tag = ""
    @bug_page = ""
  end
  
  def admins
    @users = User.where("role = 'admin'").all
    @admin_tag = "[Admin] "
    @bug_page = ""
    render :action => :new
  end
  
  def bug
    @users = User.where("role = 'admin'").all
    @admin_tag = "[Bug] "
    @bug_page = params[:url]
    render :action => :new
  end
  
  def create
    @users = params[:users_list].split(',').map {|name| User.find_by_name(name)}
    
    if params[:admin_tag]
      params[:subject] = params[:admin_tag] + params[:subject]
    end
    if params[:page]
      if params[:mail]
        params[:body] = params[:page] + '<br />' + params[:mail] + '<br />' + params[:body]
      else
        params[:body] = params[:page] + '<br />' + params[:body]
      end
    end
    
    if user_signed_in?
      current_user.send_message(@users, params[:body], params[:subject])
      redirect_to @conversation, notice: 'message_sent'
    else
      User.find(1).send_message(@users, params[:body], params[:subject])
      redirect_to action: 'index', controller: 'home', notice: 'message_sent'
    end
  end

  def update
    if params[:reply_all].present?
      last_receipt = current_user.mailbox.receipts_for(@conversation).last
      current_user.reply_to_all(last_receipt, params[:body])
    end
    redirect_to :action => :show
  end
  
  def destroy
     @conversation.move_to_trash current_user
     redirect_to conversations_path
  end
  
  def destroy_multiple
    params[:conversations].each_key do |id|
      Conversation.find(id).move_to_trash current_user
    end
    redirect_to conversations_path
  end
end

app/views/conversations/_message.html.erb
<h4><%= link_to message.sender.name, user_path(message.sender) %> - <%= message.updated_at %></h4>
<div class="well well-small">
  <%= raw message.body %>
</div>

app/views/conversations/index.html.erb
<div class="white-opacity rounded-top">

  <h1><%= t('conversation.my') %></h1>
  
  <%= link_to t('conversation.new'), new_conversation_path %><br /><br />
  
  <% if @conversations.empty? %>
    <%= t('conversation.none') %>
  <% else %>
    <%= form_tag destroy_multiple_conversations_path, method: :delete do %>
    <table class="table table-condensed">
      <thead>
      	<tr>
      	  <th></th>
          <th><%= t('conversation.subject') %></th>
      	  <th><%= t('conversation.last_sender')%></th>
      	  <th><%= t('conversation.date') %></th>
      	</tr>
      </thead>
      <tbody>
      <% @conversations.each do |conversation| %>
        <tr>
          <td><input type="checkbox" name="conversations[<%= conversation.id %>]"></td>
          <td>
            <% if conversation.is_unread?(current_user) %><i class="icon-envelope"></i><% end %>
            <%= link_to conversation.subject, conversation_path(conversation) %>
          </td>
          <td><%= link_to conversation.last_sender.name, user_path(conversation.last_sender) %></td>
          <td><%= formated_date(conversation.updated_at) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= submit_tag t('icon.destroy') %>
    <% end %>
  <% end %>

</div>

app/views/conversations/new.html.erb
<div class="span6 offset3 white-opacity rounded">
  
  <h1><%= t('conversation.new') %></h1>
  
  <%= form_tag({:action => 'create'}, :class => 'form-horizontal') do %>
  
  <%= hidden_field_tag 'admin_tag', @admin_tag %>
  
    <div class="control-group">
      <%= label_tag 'users_list', t('conversation.to'), class: 'control-label' %>
      <div class="controls">
        <div class="input-prepend">
          <input id="users_list" name="users_list" type="text" size="30"  data-path="<%= search_users_path() %>" data-pre="<%= @users.map{|u| {name: u.name}}.to_json %>" data-hint="<%= t('helpers.token_input.hint') %>" data-searching="<%= t('helpers.token_input.searching') %>" />
        </div>
      </div>
    </div>
  
    <div class="control-group">
      <%= label_tag 'subject', t('conversation.subject'), class: 'control-label' %>
      <div class="controls">
      	<% if @admin_tag.blank? %>
      	  <%= text_field_tag 'subject' %>
        <% else %>
      	  <div class="input-prepend">
            <span class="add-on"><%= @admin_tag %></span><%= text_field_tag 'subject' %>
          </div>
        <% end %>
      </div>
    </div>
    
    <% unless @bug_page.blank? %>
    <div class="control-group">
      <%= label_tag 'page', t('conversation.page'), class: 'control-label' %>
      <div class="controls">
        <%= text_field_tag 'page', @bug_page, :class => 'uneditable-input' %>
      </div>
    </div>
    <% end %>
    
    <% unless user_signed_in? %>
    <div class="control-group">
      <%= label_tag 'mail', t('conversation.mail'), class: 'control-label' %>
      <div class="controls">
        <%= text_field_tag 'mail' %>
      </div>
    </div>
    <% end %>
  
    <div class="control-group">
      <%= label_tag 'body', t('conversation.body'), class: 'control-label' %>
      <div class="controls">
        <%= text_area_tag 'body'%>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
        <%= submit_tag t('conversation.send'), :class => "btn btn-primary" %>
      </div>
    </div>
  
  <% end %>

</div>

app/views/conversations/show.html.erb
<div class="span8 offset2 white-opacity rounded">
  <h1><%= @conversation.subject %></h1>

  <strong><%= t('conversation.participants') %>:</strong>
  <%= raw (@conversation.recipients.map {|user| link_to user.name, user}).join(', ') %>
  <br/><br/>

  <% @receipts.each do |receipt| %>
    <%= render :partial => "message", :locals => {:message => receipt.message} %>
  <% end %>

  <%= form_tag conversation_path(@conversation), :method => :put do %>
    <div class="well center">
      <%= text_area_tag :body, nil, :rows => 5, :class => 'span5' %>
      <br/>
      <%= submit_tag t('conversation.reply'), :name => :reply_all, :class => 'btn btn-primary' %>
    </div>
  <% end %>

  <div class="well center">
    <%= button_to_destroy @conversation %>
  </div>
</div>