config/routes.rb
VinoSocialis::Application.routes.draw do

  scope "/(:locale)", :locale => /fr|en/ do
    
    resources :wine_racks do
      member do
        get 'place'
        get 'apply_place'
        post 'empty'
      end
    end

    resources :consumptions
    
    resources :pairings do
      collection do
        get 'search'
      end
    end
    
    resources :bottles do
      member do
        get 'consume'
        get 'place'
        get 'unplace'
      end
      collection do
        get 'not_placed'
      end
    end
      
    resources :tastings
    
    resources :estates do
      member do
        post 'validate'
        post 'unvalidate'
        get 'replace'
        post 'comment'
      end
    end

    resources :wines do
      member do
        post 'validate'
        post 'unvalidate'
        get 'taste'
        get 'tastings'
        get 'encave'
        get 'replace'
        get 'add_label'
        post 'comment'
      end
      collection do
        get 'recommanded'
      end
    end

    resources :wine_colors

    resources :countries do
      member do
        post 'comment'
      end
    end
    resources :regions do
      member do
        post 'comment'
      end
    end
    resources :areas do
      member do
        post 'comment'
      end
    end
    resources :superficies
    resources :volumes
    resources :color_volumes
    resources :area_color_grapes
    
    resources :grape_varieties do
      member do
        post 'validate'
        get 'replace'
        post 'do_replace'
      end
    end
  
    devise_for :users
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'stat'
        get 'dashboard'
        get 'become'
        get 'tags'
        get 'tastings'
        get 'books'
        get 'follow'
        get 'unfollow'
        get 'friends'
      end
    end
    
    resources :conversations do
      collection do
        get 'admins'
        get 'bug'
        delete 'destroy_multiple'
      end
    end
    
    resources :glossaries
    
    resources :moderations do
      collection do
        get 'sheets'
        get 'labels'
        get 'books'
        get 'clean'
        get 'proposals'
      end
    end
    
    resources :wines_and_estates do
      collection do
        get 'search'
      end
    end
    
    resources :labels do
      member do
        post 'validate'
      end
    end
    
    resources :vintages do
      collection do
        post 'rate'
      end
    end
    
    resources :proposals do
      member do
        post 'close'
      end
    end
    
    resources :books do
      member do
        post 'validate'
        get 'own'
        post 'comment'
      end
    end
    resources :book_ratings
    
    root :to => "home#index"

    match '/why', :to => "home#why"
    match '/about', :to => "home#about"
    match '/discover', :to => "home#discover"
    match '/temperature', :to => "home#temperature"
    match '/track', :to => "home#track"
    match '/share', :to => "home#share"
    match '/newcomer', :to => "home#newcomer"
    match '/sitemap', :to => "home#sitemap"
  end

  match '', :to => redirect { |p, r| p[:locale] ? "/#{p[:locale]}/" : '/fr/' }
  
  match '/areas/for_region_id/:region_id' => 'areas#for_region_id'
  
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  belongs_to :wine
  belongs_to :user
  has_many :wine_rack_positions, dependent: :restrict
  has_many :consumptions, dependent: :restrict
  
  acts_as_taggable
  
  validates :initial_quantity, :numericality => { :only_integer => true, :greater_than => 0 }
  validates :price, :numericality => { :greater_than_or_equal_to => 0 }
  validates :current_value, :numericality => { :greater_than_or_equal_to => 0 }
  validates :drink_min, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates :drink_max, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates :drink_best, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  
  scope :remain, lambda {|user| where('bottles.user_id = ? AND remaining_quantity > 0', user.id)}
  scope :rack, lambda {|rack| joins(:wine_rack_positions).where('"wine_rack_positions".wine_rack_id = ?', rack).group('"bottles".id')}
  scope :remaining_as_quantity, select('bottles.*, remaining_quantity AS quantity')
  scope :in_rack_as_quantity, select('bottles.*, count("wine_rack_positions".id) AS quantity')
  
  scope :best, where('vintage > 0 AND vintage + drink_best = ?', Time.now.year)
  scope :ready, where('vintage > 0 AND vintage + drink_min <= ? AND vintage + drink_max >= ?', Time.now.year, Time.now.year)
  scope :too_late, where('vintage > 0 AND vintage + drink_max < ?', Time.now.year)
  scope :too_soon, where('vintage > 0 AND vintage + drink_min > ?', Time.now.year)
  
  scope :color, lambda {|color| joins(:wine).where('"wines".wine_color = ?', color)}
  
  scope :name_like, lambda {|name| joins(:wine => :estate).select('"bottles".*').where('"estates".name ILIKE ? OR "wines".name ILIKE ?', "%#{name}%", "%#{name}%")}
  scope :area_like, lambda {|name| joins(:wine => {:area => {:region => :country}}).select('"bottles".*').where('"countries".name ILIKE ? OR "regions".name ILIKE ? OR "areas".name ILIKE ?', "%#{name}%", "%#{name}%", "%#{name}%")}
  scope :comments_like, lambda {|name| where('comments ILIKE ? OR channel_comments ILIKE ?', "%#{name}%", "%#{name}%")}
  
  scope :wine_order, lambda {|sens| joins(:wine => :estate).order('"estates".name ' + sens + ', "wines".name ' + sens)}
  scope :area_order, lambda {|sens| joins(:wine => {:area => {:region => :country}} ).order('"countries".name ' + sens + ', "regions".name ' + sens + ', "areas".name ' + sens)}
  scope :color_order, lambda {|sens| joins(:wine).order('"wines".wine_color ' + sens)}
  scope :other_order, lambda {|attribute, sens| order(attribute + ' ' + sens)}
  
  def placed
    WineRackPosition.where('bottle_id = ?', id).count
  end
  
  def not_placed
    remaining_quantity - placed
  end
  
  def positions_in(rack)
    WineRackPosition.where('bottle_id = ? AND wine_rack_id = ?', id, rack.id)
  end
  
  def distance(other)
    return 1 if self.wine.wine_color != other.wine.wine_color
    return 0.8 if self.wine.area.region.id != other.wine.area.region.id
    return 0.6 if self.wine.area.id != other.wine.area.id
    
    bonus_vintage = (self.vintage == other.vintage ? 0.1 : 0)
    return 0.4 - bonus_vintage if self.wine.estate.id != other.wine.estate.id
    return 0.2 - bonus_vintage if self.wine.id != other.wine.id
    return 0.1 - bonus_vintage
  end
  
  def drink_min_year
    vintage.to_i == 0 ? 0 : vintage.to_i + drink_min.to_i
  end
  
  def drink_max_year
    vintage.to_i == 0 ? 0 : vintage.to_i + drink_max.to_i
  end
  
  def drink_best_year
    vintage.to_i == 0 ? 0 : vintage.to_i + drink_best.to_i
  end
  
  def drink
    return 'ready' if vintage.to_i == 0
    year = Time.now.year
    return 'best' if year == drink_best_year
    return 'too_soon' if year < drink_min_year
    return 'too_late' if year > drink_max_year
    return 'ready'
  end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /bottles
  def index
    @bottles = Bottle.remain(current_user)

    if (@bottles.empty?)
      redirect_to new_bottle_path
    end
    
    if params[:maturity]
      if params[:maturity] == 'best'
        @bottles = @bottles.best
      elsif params[:maturity] == 'too_late'
        @bottles = @bottles.too_late
      elsif params[:maturity] == 'too_soon'
        @bottles = @bottles.too_soon
      elsif params[:maturity] == 'ready'
        @bottles = @bottles.ready
      end
    end
    
    if params[:color]
      @bottles = @bottles.color(params[:color])
    end
    
    if params[:tag]
      @bottles = @bottles.tagged_with(params[:tag])
    end
    
    if params[:wine_rack_id] && (params[:wine_rack_id] != '0')
      @bottles = @bottles.rack(Integer(params[:wine_rack_id])).in_rack_as_quantity
    else
      @bottles = @bottles.remaining_as_quantity
    end
    
    if params[:ids]
      @bottles = @bottles.find(params[:ids].split(",").map { |s| s.to_i })
    end
    
    if params[:search_attribute] == 'wine'
      @bottles = @bottles.name_like(params[:search_value])
    elsif params[:search_attribute] == 'area'
      @bottles = @bottles.area_like(params[:search_value])
    elsif params[:search_attribute] == 'comments'
      @bottles = @bottles.comments_like(params[:search_value])
    end
    
    if params[:order_attribute] == 'name'
      @bottles = @bottles.wine_order(params[:order_sens])
    elsif params[:order_attribute] == 'area'
      @bottles = @bottles.area_order(params[:order_sens])
    elsif params[:order_attribute] == 'wine_color'
      @bottles = @bottles.color_order(params[:order_sens])
    elsif params[:order_attribute]
      @bottles = @bottles.other_order(params[:order_attribute], params[:order_sens])
    end
    
    @racks = WineRack.where('user_id = ?', current_user.id)
  end
  
  def not_placed
    @bottles = Bottle.select('*, remaining_quantity AS quantity').where('bottles.user_id = ? AND remaining_quantity > 0', current_user.id)
    @bottles.each {|b| b.quantity = b.not_placed}
    @bottles = @bottles.find_all {|b| b.quantity > 0}
    @racks = WineRack.where('user_id = ?', current_user.id)
    @not_placed = true
    render action: 'index'
  end
  
  # GET /bottles/1
  def show
    @wine_racks = WineRack.joins(:wine_rack_positions).select('"wine_racks".id, name, count("wine_rack_positions".id) AS positions').where('"wine_rack_positions".bottle_id = ?', @bottle.id).group('"wine_racks".id')
    @all_wine_racks = WineRack.where('user_id = ?', current_user.id)
  end

  # GET /bottles/new
  def new
    if params[:wine].blank?
      redirect_to wines_and_estates_path, alert: 'select_wine_for_new_bottle'
    else
      @wine = Wine.find(params[:wine])
    end
  end
  
  # GET /bottles/1/edit
  def edit
    @wine = @bottle.wine
  end

  # POST /bottles
  def create
    @bottle.user_id = current_user.id
    @bottle.remaining_quantity = @bottle.initial_quantity
    if @bottle.save
      redirect_to @bottle, notice: 'bottle_created'
    else
      @wine = @bottle.wine
      render action: "new"
    end
  end
  
  # PUT /bottles/1
  def update
    if @bottle.update_attributes(params[:bottle])
      redirect_to @bottle, notice: 'bottle_updated'
    else
      @wine = @bottle.wine
      render action: "edit"
    end
  end
  
  # DELETE /bottles/1
  def destroy
    @bottle.destroy
    redirect_to bottles_url
  end
  
  # POST /bottles/1/consume
  def consume
    if params[:wine_rack_position_id].blank?
      redirect_to new_consumption_path(:bottle => @bottle)
    else
      redirect_to new_consumption_path(:bottle => @bottle, :wine_rack_position_id => params[:wine_rack_position_id])
    end
  end
  
  def place
    redirect_to place_wine_rack_path(WineRack.find(params[:wine_rack_id]), :bottle => @bottle, :quantity => params[:quantity])
  end
  
  def unplace
    WineRackPosition.find(params[:wine_rack_position_id]).destroy()
    redirect_to @bottle , notice: 'bottle_unplaced'
  end
end

app/helpers/bottles_helper.rb
module BottlesHelper
  
  def bottle_name(bottle, options = {})
    html ||= options[:html]
    wine_name(bottle.wine, estate: true, area: true, html: html) + " - " + formated_vintage(bottle.vintage, false).to_s
  end
  
  def bottles_count_remaining
    Bottle.sum(:remaining_quantity)
  end
end

app/views/bottles/_bottle.html.erb
<tr id="bottle" style="cursor:pointer;">
  <input type="hidden" value="<%= bottle_path(bottle) %>" />
  <td id="name_<%= bottle.id %>" style="vertical-align:middle;">
    <%= image_tag bottle.wine.labels.validated.first.image_url(:micro).to_s, class: 'pull-right' if bottle.wine.labels.validated.any? %>
  	<%= wine_name bottle.wine, estate: true, area: false, html: true, separator: raw('<br />') %> 
  </td>
  <td id="area_<%= bottle.id %>" style="vertical-align:middle;">
  	<%= full_area_name bottle.wine.area, html: true, separator2: raw('<br />') %>
  </td>
  <td id="wine_color_<%= bottle.id %>" style="vertical-align:middle;">
    <%= wine_icon bottle.wine, text: true %>
  </td>
  <td id="vintage_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <span><%= formated_vintage(bottle.vintage) %></span>
  </td>
  <td id="drink_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= t(bottle.drink, scope: 'bottles.drink') %>
  </td>
  <td id="remaining_quantity<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
  	<span id="raw"><%= bottle.quantity %></span> (<%= bottle.volume %>)
  </td>
  <td id="price_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <span id="raw" style="visibility: hidden;position: absolute;"><%= bottle.price%></span><span><%= formated_price(bottle.price) %></span>
  </td>
  <td id="current_value_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <span id="raw" style="visibility: hidden;position: absolute;"><%= bottle.current_value%></span><span><%= formated_price(bottle.current_value) %></span>
  </td>
  <td id="date_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= formated_date(bottle.date) %>
  </td>
  <td id="channel_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= t(bottle.channel, scope: 'bottles.channels') %>
  </td>
  <td id="chancomm_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= bottle.channel_comments %>
  </td>
  <td id="comments_<%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= bottle.comments %>
  </td>
  <td id="grape_varieties <%= bottle.id %>" style="text-align:center;vertical-align:middle;">
    <%= bottle.wine.grape_varieties.map(&:name).join(', ') %>
  </td>
</tr>

app/views/bottles/_form.html.erb
<h2><%= wine_name(@wine, estate: true, area: true) %></h2>

<%= form_for(@bottle, html: { class:'form-horizontal'}) do |f| %>
  <%= f.hidden_field :wine_id, value: @wine.id %>
  <div class="row-fluid">
    
    <div class="span6">
      <div class="control-group">
        <%= f.label :vintage, :class => 'control-label' %>
        <div class="controls">
          <%= select_vintage f, @bottle.vintage %>
        </div>
      </div>
      
      <div class="control-group">
        <% volumes = ['20 cl', '25 cl', '37.5 cl', '50 cl', '62 cl', '62.5 cl', '75 cl', '1 l', '1.5 l', '3 l', '4.5 l', '5 l', '6 l', '9 l', '12 l', '15 l', '18 l'] %>
        <%= f.label :volume, :class => 'control-label' %>
        <div class="controls">
          <%= select_tag 'bottle[volume]', options_for_select(volumes, :selected => (@bottle.volume ? @bottle.volume : '75 cl')) %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :initial_quantity, :class => 'control-label' %>
        <div class="controls">
          <%= f.number_field :initial_quantity, autocomplete: 'off' %>
        </div>
      </div>
      
      <% drink_hints = @wine.drink_hint %>
      <div class="control-group">
        <%= f.label t('helpers.label.bottle.drink'), :class => 'control-label' %>
        <div class="controls">
          <% min = f.number_field(:drink_min, autocomplete: 'off', class: 'input-micro') %>
          <% max = f.number_field(:drink_max, autocomplete: 'off', class: 'input-micro') %>
          <%= raw t('helpers.label.bottle.drink_inputs', min: min, max: max) %>
          <% if drink_hints[:based_on] > 0 %>
            <% title = t('helpers.label.bottle.hint_title', count: drink_hints[:based_on]) %>
            <% hint = t('helpers.label.bottle.drink_inputs', min: drink_hints[:min], max: drink_hints[:max]) %>
            <a href="#" id="drink_min_max_hint" rel="popover" title="<%= title %>" data-content="<%= hint %>"><i class="icon-flag"></i></a>
          <% end %>
          <br />
          <% min = '<span id="drink_min_result">-</span>' %>
          <% max = '<span id="drink_max_result">-</span>' %>
          <%= raw t('helpers.label.bottle.drink_years', min: min, max: max) %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :drink_best, :class => 'control-label' %>
        <div class="controls">
          <% input = f.number_field(:drink_best, autocomplete: 'off', class: 'input-micro') %>
          <% result = '<span id="drink_best_result">-</span>' %>
          <%= raw t('helpers.label.bottle.years', input: input, result: result) %>
          <% if drink_hints[:based_on] > 0 %>
            <% title = t('helpers.label.bottle.hint_title', count: drink_hints[:based_on]) %>
            <% hint = t('helpers.label.bottle.years_only', best: drink_hints[:best]) %>
            <a href="#" id="drink_best_hint" rel="popover" title="<%= title %>" data-content="<%= hint %>"><i class="icon-flag"></i></a>
          <% end %>
        </div>
      </div>
      
      <div class="control-group">
        <%= f.label :comments, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_area :comments, :rows => 3 %>
        </div>
      </div>
    
    </div>
    
    <div class="span6">
	
  	  <div class="control-group">
        <%= f.label :date, :class => 'control-label' %>
  	    <div class="controls">
  	      <%= f.text_field :date, value: l(@bottle.date.nil? ? Date.today : @bottle.date), :locale => I18n.locale %>
  	    </div>
  	  </div>
  	
  	  <div class="control-group">
        <% channels = ['producer', 'gift', 'fair', 'exchange', 'store', 'supermarket', 'bulk_order'].map {|c| [t(c, scope: 'bottles.channels'), c]}%>
        <%= f.label :channel, :class => 'control-label' %>
  	    <div class="controls">
          <%= select_tag 'bottle[channel]', options_for_select(channels, :selected => (@bottle.channel ? @bottle.channel : 'producer')) %>
  	    </div>
  	  </div>
    
      <div class="control-group">
        <%= f.label :channel_comments, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :channel_comments %>
        </div>
      </div>
  	
  	  <div class="control-group">
        <%= f.label :price, :class => 'control-label' %>
  	    <div class="controls">
  	      <div class="input-prepend">
            <span class="add-on"><%= current_user.currency %></span><%= f.text_field :price, value: formated_price(@bottle.price ? @bottle.price : '0', form = true), autocomplete: 'off' %>
          </div>
  	    </div>
  	  </div>
    
      <div class="control-group">
        <%= f.label :current_value, :class => 'control-label' %>
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><%= current_user.currency %></span><%= f.text_field :current_value, value: formated_price(@bottle.current_value ? @bottle.current_value : '0', form = true), autocomplete: 'off' %>
          </div>
        </div>
      </div>
    
      <div class="control-group">
        <%= f.label :tag_list, :class => 'control-label' %>
        <div class="controls">
          <div class="input-prepend">
            <%= f.text_field :tag_list, :"data-path" => tags_user_path(current_user), :"data-pre" => @bottle.tags.map(&:attributes).to_json, :"data-hint" => t('helpers.token_input.hint'), :"data-searching" => t('helpers.token_input.searching') %>
          </div>
        </div>
      </div>
    
      <div class="control-group">
        <div class="controls">
          <%= f.submit class: "btn btn-primary span6" %>
          <div class="alert"><%= t('helpers.private') %></div>
        </div>
      </div>
      </div>
      
    </div>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<div class="white-opacity rounded">
  <h1><%= t("bottles.edit") %></h1>
  <%= render 'form' %>
</div>

app/views/bottles/new.html.erb
<div class="white-opacity rounded">
  <h1><%= t("bottles.new") %></h1>
  <%= render 'form' %>
</div>

app/views/bottles/show.html.erb
<div class="white-opacity rounded">

<h1><%= bottle_name @bottle %></h1>

<div class="row-fluid">
  <div class="span5">
    <b><%= link_to @bottle.wine.estate.name, @bottle.wine.estate %></b><br />
    <%= raw "<i class=\"icon-home\"></i> #{link_to(@bottle.wine.estate.www, @bottle.wine.estate.www, target: '_blank')}" unless @bottle.wine.estate.www.empty? %>
    <br /><br />
    <b><%= link_to @bottle.wine.name, @bottle.wine %></b><br />
    <%= full_area_name @bottle.wine.area, html: true %><br />
    <%= wine_icon @bottle.wine, text: true %><br />
    <% unless @bottle.wine.grape_varieties.blank? %>
      <%= @bottle.wine.grape_varieties.map(&:name).join(', ') %><br />
    <% end %>
    <% unless @bottle.wine.temperature.blank? %>
      <%= t("helpers.label.wine.temperature") %> : <%= @bottle.wine.temperature %><br />
    <% end %>
    
    <br /><br /><br />
    
    <!--                                         PLACED BOTTLES                                         -->
    <table class="table table-condensed">
      <% @wine_racks.each do |rack| %>
        <% unless rack.positions == 0 %>
          <tr>
            <td><%= link_to rack.name, wine_rack_path(rack, :bottle => @bottle) %></td>
            <td><%= t('bottles.placed', count: rack.positions) %></td>
          </tr>
        <% end %>
      <% end %>
    
    <!--                                        UNPLACED BOTTLES                                        -->
    <% not_placed = @bottle.not_placed %>
    <% if not_placed == 0 %>
      </table>
    <% else %>
        <tr>
          <td><%= link_to t('bottles.unplaced'), not_placed_bottles_path %></td>
          <td><%= t('bottles.placed', count: not_placed) %></td>
        </tr>
      </table>
      <% if @all_wine_racks.empty? %>
        <br /><%= link_to t('wine_rack.new'), new_wine_rack_path %><br /><br />
      <% else %>
        <%= form_for @bottle, :url => {:action => 'place'}, :html => {:class => 'form-inline', :method => 'get'} do %>
          <% if not_placed > 1 %>
            <%= select_tag 'quantity', options_for_select((1..not_placed).map {|q| [t('bottles.placed', count: q), q]}) %><br />
          <% else %>
            <%= hidden_field_tag 'quantity', 1 %>
          <% end %>
          <%= select_tag 'wine_rack_id', options_for_select(@all_wine_racks.map {|r| [r.name, r.id]}) %>
          <%= submit_tag t('bottles.place'), class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class="span1">
    <% if @bottle.wine.labels.validated.any? %>
      <% @bottle.wine.labels.validated.each do |label| %>
        <%= image_tag label.image_url(:small).to_s, style: 'border: 1px solid;' %><br />
      <% end %>
    <% end %>
  </div>

  <div class="span6">
	<dl class="dl-horizontal">
	  <dt><%= t("helpers.label.bottle.remaining_quantity")%></dt>
	  <dd><%= t("bottles.remaining_and_initial", :remaining => @bottle.remaining_quantity, :initial => @bottle.initial_quantity) %> (<%= @bottle.volume %>)</dd>
	  
	  <br />
	
    <% min = formated_vintage(@bottle.drink_min_year, true) %>
    <% max = formated_vintage(@bottle.drink_max_year, true) %>
    <dt><%= t("helpers.label.bottle.drink")%></dt>
    <dd><%= t("helpers.label.bottle.drink_years", min: min, max: max) %></dd>
    
    <dt><%= t("helpers.label.bottle.drink_best")%></dt>
    <dd><%= formated_vintage(@bottle.drink_best_year, true) %></dd>
    
    <br />
    
	  <dt><%= t("helpers.label.bottle.date")%></dt>
	  <dd><%= formated_date(@bottle.date) %></dd>
  
    <dt><%= t("helpers.label.bottle.channel")%></dt>
    <dd><%= t(@bottle.channel, scope: 'bottles.channels') %></dd>
  
    <dt><%= t("helpers.label.bottle.channel_comments")%></dt>
    <dd><%= @bottle.channel_comments %>&nbsp;</dd>
  
    <dt><%= t("helpers.label.bottle.price")%></dt>
    <dd><%= formated_price(@bottle.price) %></dd>
  
    <dt><%= t("helpers.label.bottle.current_value")%></dt>
    <dd><%= formated_price(@bottle.current_value) %></dd>
    
	  <% unless @bottle.comments.blank? %>
	    <br />
  	  <dt><%= t("helpers.label.bottle.comments")%></dt>
  	  <dd><%= @bottle.comments %></dd>
  	<% end %>
	</dl>
	
	<% unless @bottle.tag_list.empty? %>
	  <%= raw @bottle.tag_list.map {|tag| link_to tag, bottles_path(tag: tag)}.join(', ') %>
	  <br /><br />
	<% end %>

	<%= button_to_consume consume_bottle_path(@bottle) %> <%= button_to_edit edit_bottle_path(@bottle) %> <%= button_to_destroy @bottle if @bottle.can_destroy? %>
  </div>
</div>

</div>