config/routes.rb
VinoSocialis::Application.routes.draw do

  scope "/(:locale)", :locale => /fr|en/ do
    
    resources :wine_racks do
      member do
        get 'place'
        get 'apply_place'
        post 'empty'
      end
    end

    resources :consumptions
    
    resources :pairings do
      collection do
        get 'search'
      end
    end
    
    resources :bottles do
      member do
        get 'consume'
        get 'place'
        get 'unplace'
      end
      collection do
        get 'not_placed'
      end
    end
      
    resources :tastings
    
    resources :estates do
      member do
        post 'validate'
        post 'unvalidate'
        get 'replace'
        post 'comment'
      end
    end

    resources :wines do
      member do
        post 'validate'
        post 'unvalidate'
        get 'taste'
        get 'tastings'
        get 'encave'
        get 'replace'
        get 'add_label'
        post 'comment'
      end
      collection do
        get 'recommanded'
      end
    end

    resources :wine_colors

    resources :countries do
      member do
        post 'comment'
      end
    end
    resources :regions do
      member do
        post 'comment'
      end
    end
    resources :areas do
      member do
        post 'comment'
      end
    end
    resources :superficies
    resources :volumes
    resources :color_volumes
    resources :area_color_grapes
    
    resources :grape_varieties do
      member do
        post 'validate'
        get 'replace'
        post 'do_replace'
      end
    end
  
    devise_for :users
    resources :users do
      collection do
        get 'search'
      end
      member do
        get 'stat'
        get 'dashboard'
        get 'become'
        get 'tags'
        get 'tastings'
        get 'books'
        get 'follow'
        get 'unfollow'
        get 'friends'
      end
    end
    
    resources :conversations do
      collection do
        get 'admins'
        get 'bug'
        delete 'destroy_multiple'
      end
    end
    
    resources :glossaries
    
    resources :moderations do
      collection do
        get 'sheets'
        get 'labels'
        get 'books'
        get 'clean'
        get 'proposals'
      end
    end
    
    resources :wines_and_estates do
      collection do
        get 'search'
      end
    end
    
    resources :labels do
      member do
        post 'validate'
      end
    end
    
    resources :vintages do
      collection do
        post 'rate'
      end
    end
    
    resources :proposals do
      member do
        post 'close'
      end
    end
    
    resources :books do
      member do
        post 'validate'
        get 'own'
        post 'comment'
      end
    end
    resources :book_ratings
    
    root :to => "home#index"

    match '/why', :to => "home#why"
    match '/about', :to => "home#about"
    match '/discover', :to => "home#discover"
    match '/temperature', :to => "home#temperature"
    match '/track', :to => "home#track"
    match '/share', :to => "home#share"
    match '/newcomer', :to => "home#newcomer"
    match '/sitemap', :to => "home#sitemap"
  end

  match '', :to => redirect { |p, r| p[:locale] ? "/#{p[:locale]}/" : '/fr/' }
  
  match '/areas/for_region_id/:region_id' => 'areas#for_region_id'
  
  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if (!current_user.nil?)
      redirect_to dashboard_user_path(current_user)
    else
      @wines = Wine.unscoped.validated.last(5)
      @tastings = Tasting.last(4)
    end
  end
  
  def discover
    @areas = Area.reorder("random()").limit(7)
    @grape_varieties = GrapeVariety.reorder("random()").limit(9)
    @definitions = Glossary.reorder("random()").limit(2)
    @vintages = Vintage.select("area, year, count(user_id) AS users, avg(note) AS note").group("area, year").reorder("random()").limit(9)
    @book = Book.reorder("random()").limit(1)
  end
  
  def temperature
  end
  
  def track
  end
  
  def share
    @sheeters = Wine.unscoped.validated.select('user_id, COUNT(id) AS total').group('user_id').order('total DESC').limit(3)
    @sheeters = @sheeters.map {|wine| {:name => wine.user.name, :count => wine.total}}
    @tasters = Tasting.unscoped.select('user_id, COUNT(id) AS total').group('user_id').order('total DESC').limit(3)
    @tasters = @tasters.map {|tasting| {:name => tasting.user.name, :count => tasting.total}}
  end
  
  def about
  end
  
  def why
  end
  
  def newcomer
    @estate = Estate.find(2)
    @wine = @estate.wines.first
  end
  
  def sitemap
    @estates = Estate.validated
    @wines = Wine.validated
    @books = Book.validated
    respond_to do |format|
       format.xml
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_announcement.html.erb
<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert alert-error">
    ×
  </button>
  <p>
    <strong>Annonce générale</strong>
  </p>
  <p>
    Bienvenue dans le monde du vin sur Vinosus !<br />
    Le site est actuellement en bêta et peut présenter quelques ralentissements ponctuellement, notament au premier chargement du site.<br />
    Merci de signaler tout problème ou bug. Les commentaires sur l'ergonomie, le design, l'attractivité ou les fonctionnalités sont également appréciés.<br />
    Bonne découverte !
  </p>
</div>

app/views/home/about.html.erb
<% set_meta_tags :title => t("footer.about") %>

<div class="white-opacity rounded">
  <p>Vinosus est entièrement gratuit (et espère le rester).</p>
  <p>Vinosus a pour but de faire découvrir le monde du vin, accompagner les débutants et fournir tous les outils dont rêvent les amateurs de vin.</p>
  <p>Toute personne physique ou morale peut contacter les administrateurs du site pour toutes données le concernant.</p>
  <p>Les commentaires et appréciations des vins sont émis par les utilisateurs et n'engagent donc pas la responsabilité de Vinosus.</p>
  <p>L'intégralité des données est la propriété de Vinosus. L'extraction ou la réutilisation des données sans autorisation est strictement interdit.</p>
  <p>Contact: <%= mail_to 'guillaume.juillot@gmail.com', 'Guillaume Juillot' %></p>
</div>

app/views/home/discover.html.erb
<% description = t('home.discover.areas.title_areas', count: Area.count) %>
<% description += ' - ' + t('home.discover.grape_varieties.title', count: GrapeVariety.count) %>
<% description += ' - ' + t('temperature.title') %>
<% description += ' - ' + t('home.discover.glossary.title', count: Glossary.count) %>
<% description += ' - ' + t('vintages.vintages') %>
<% description += ' - ' + t('home.discover.recommanded.title') %>
<% description += ' - ' + t('home.discover.pairings.title') %>

<% set_meta_tags :title => t("home.index.carousel.t2"),
                 :description => description %>

<div class="row-fluid">
  <div class="span4">
    <div class="alert alert-no-close alert-info" style="height: 240px; position: relative">
      <h3><%= t('home.discover.areas.title_countries', count: Country.count) %></h3>
      <h3><%= t('home.discover.areas.title_areas', count: Area.count) %></h3>
      <%= raw @areas.map {|a| link_to (a.region.country.name + ' - ' + a.name).truncate(40), a}.join('<br />') %><br />
      <%= link_to t('home.discover.more'), countries_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-no-close alert-success" style="height: 240px; position: relative">
      <h3><%= t('home.discover.grape_varieties.title', count: GrapeVariety.count) %></h3>
      <%= raw @grape_varieties.map {|a| link_to a.name.truncate(36), a}.join('<br />') %><br />
      <%= link_to t('home.discover.more'), grape_varieties_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-no-close alert-info" style="height: 240px; position: relative">
      <h3><%= t('temperature.title') %></h3>
      <%= t('temperature.introduction.introduction') %>
      <ul>
        <li><%= t('temperature.introduction.cold') %></li>
        <li><%= t('temperature.introduction.hot') %></li>
      </ul>
      <%= link_to t('home.discover.more'), temperature_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span5">
    <div class="alert alert-no-close alert-success" style="height: 240px; text-align: justify; position: relative">
      <h3><%= t('home.discover.glossary.title', count: Glossary.count) %></h3>
      <% @definitions.each do |definition| %>
        <em><%= definition.word.truncate(50) %></em><br /><%= definition.definition.truncate(150) %><br /><br />
      <% end %>
      <%= link_to t('home.discover.more'), glossaries_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-no-close alert-info" style="height: 240px; text-align: justify; position: relative">
      <h3><%= t('vintages.vintages') %></h3>
      <% @vintages.each do |vintage| %>
        <span data-score="<%= vintage.note %>" class="vintage_note"></span>&nbsp;&nbsp;&nbsp;&nbsp;<%= "#{vintage.area.truncate(18)}, #{vintage.year}" %><br />
      <% end %>
      <%= link_to t('home.discover.more'), vintages_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span3">
    <div class="alert alert-no-close alert-success" style="height: 240px; text-align: justify; position: relative">
      <h3><%= t('menu.discover.books') %></h3>
      <%= render @book %>
      <%= link_to t('home.discover.more'), books_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span4">
    <div class="alert alert-no-close alert-success" style="height: 250px; text-align: justify;position: relative">
      <h3><%= t('home.discover.recommanded.title') %></h3>
      <%= t('home.discover.recommanded.description') %><br />
      <%= image_tag 'why/recommandation.jpg', style: "position: relative; top: 7px;" %><br />
      <%= link_to t("menu.profile.sign_up"), new_user_registration_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-no-close alert-info" style="height: 250px; text-align: justify;position: relative">
      <h3><%= t('home.discover.pairings.title') %></h3>
      <%= t('home.discover.pairings.description') %><br />
      <%= image_tag 'why/pairing.jpg', style: "position: relative; top: 7px;" %><br />
      <%= link_to t("menu.profile.sign_up"), new_user_registration_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-no-close alert-success" style="height: 250px; text-align: justify;position: relative">
      <h3><%= t('home.discover.community.title') %></h3>
      <ul>
        <li><%= t('home.discover.community.users', count: User.count) %></li>
        <li><%= t('home.discover.community.wines', count: Wine.validated.count) %></li>
        <li><%= t('home.discover.community.tastings', count: Tasting.count) %></li>
        <li><%= t('book.sheets', count: Book.validated.count) %></li>
      </ul>
      <%= link_to t("menu.profile.sign_up"), new_user_registration_path, class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<% set_meta_tags :title => t("home.index.title"),
                 :description => t("home.index.description") %>

<div class="row-fluid">
  <div class="span6">
    <%= image_tag 'home/vinosus.jpg' %>
    <br />
    <div class="alert alert-no-close alert-success" style="line-height: 1.30; position: relative; height: 200px">
      <h3><%= t('home.index.for_all') %></h3><br />
      <p><%= raw t('home.index.carousel.p1') %></p>
      <%= link_to t('home.discover.more'), url_for(controller: 'home', action: 'why'), class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
   </div> 
   
  <div class="span6">
    <%= image_tag 'home/discover.jpg' %>
    <br />
    <div class="alert alert-no-close alert-success" style="line-height: 1.30; position: relative; height: 200px">
      <h3><%= t('menu.discover.title') %></h3>
      <p>
        <%= raw t('home.index.discover.p1') %><br />
        <%= raw t('home.index.discover.p2') %>
      </p>
      <p><%= raw t('home.index.carousel.p2') %></p>
      <%= link_to t('home.discover.more'), url_for(controller: 'home', action: 'discover'), class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
</div>

<div class="row-fluid">
  <div class="span6">
    <%= image_tag 'home/track.jpg' %>
    <br />
    <div class="alert alert-no-close alert-success" style="line-height: 1.30; position: relative; height: 200px">
      <h3><%= t('menu.track.title') %></h3>
      <p>
        <%= raw t('home.index.track.p1') %>
      </p>
      <p><%= raw t('home.index.carousel.p3') %></p>
      <%= link_to t('home.discover.more'), url_for(controller: 'home', action: 'track'), class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>

  <div class="span6">
    <%= image_tag 'home/share.jpg' %>
    <br />
    <div class="alert alert-no-close alert-success" style="line-height: 1.30; position: relative; height: 200px">
      <p>
        <h3><%= t('menu.share.title') %></h3>
        <%= raw t('home.index.share.p2') %><br />
        <%= raw t('home.index.share.p3') %>
      </p>
      <p><%= raw t('home.index.carousel.p4') %></p>
      <%= link_to t('home.discover.more'), url_for(controller: 'home', action: 'share'), class: 'btn btn-primary', style: 'position: absolute; bottom: 15px; right: 15px' %>
    </div>
  </div>
</div>


<hr />

<div class="row">
  <div class="span6">
    <div class="alert alert-no-close alert-success">
      <h3><%= t('home.index.discover.l3', :c => wine_count_validated) %></h3>
      <table class="table">
        <% @wines.each do |wine| %>
          <tr>
            <td>
              <% if wine.labels.validated.any? %>
                <%= image_tag wine.labels.validated.first.image_url(:mini).to_s, style: "border: 1px solid;" %>
              <% end %>
            </td>
            <td>
              <%= wine_name(wine, estate: true, html: true) %><br />
              <%= full_area_name wine.area, html: true %><br />
              <%= wine_icon wine, text: true %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="span6">
    <div class="alert alert-no-close alert-success">
      <h3><%= t('home.index.share.l2', :c => Tasting.all.count) %></h3>
      <table class="table">
        <% @tastings.each do |tasting| %>
          <tr>
            <td>
              <% if tasting.wine.labels.validated.any? %>
                <%= image_tag tasting.wine.labels.validated.first.image_url(:mini).to_s, style: "border: 1px solid;" %>
              <% end %>
            </td>
            <td>
              <%= wine_name(tasting.wine, estate: true, html: true) %><br />
              <%= full_area_name tasting.wine.area, html: true %><br />
              <%= wine_icon tasting.wine, text: true %><br />
              <%= formated_vintage tasting.vintage, false %><br />
              <span class="star" data-score="<%= tasting.note %>"></span> par <%= tasting.user.name %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/home/newcomer.html.erb
<% current_user.tutorial = false %>

<div class="row-fluid">
  <div class="span4">
    <div class="white-opacity rounded" style="height: 150px">
      <h1><%= t "menu.discover.title" %></h1>
      Pour découvrir le monde du vin :<br />
      <%= link_to raw('<i class="icon-list"></i> ') + t("menu.discover.wines_estates"), wines_and_estates_path %><br />
      <%= link_to raw('<i class="icon-book"></i> ') + t("menu.discover.glossaries"), glossaries_path %><br />
      <%= link_to raw('<i class="icon-thumbs-up"></i> ') + t("menu.discover.recommmandations"), recommanded_wines_path %><br />
      <%= link_to raw('<i class="icon-random"></i> ') + t("menu.discover.pairings"), pairings_path %><br />
      et bien plus encore...
    </div>
  </div>
  <div class="span4">
    <div class="white-opacity rounded" style="height: 150px">
      <h1><%= t "menu.track.title" %></h1>
      Pour suivre vos bouteilles et vos dégustations :<br />
      <%= link_to raw('<i class="icon-bottles"></i> ') + t("menu.track.my_bottles"), bottles_path %><br />
      <%= link_to raw('<i class="icon-th"></i> ') + t("menu.track.my_racks"), wine_racks_path %><br />
      <%= link_to raw('<i class="icon-tastings"></i> ') + t("menu.track.my_tastings"), tastings_user_path(current_user) %>
    </div>
  </div>
  <div class="span4">
    <div class="white-opacity rounded" style="height: 150px">
      <h1><%= t "menu.share.title" %></h1>
      Pour pour partager avec les autres utilisateurs :<br />
      <%= link_to raw('<i class="icon-user"></i> ') + t("menu.share.users"), users_path %><br />
      <%= link_to raw('<i class="icon-share"></i> ') + t("menu.share.new_wine"), new_wine_path %><br />
      <%= link_to raw('<i class="icon-glass"></i> ') + t("menu.share.taste"), new_tasting_path %>
    </div>
  </div>
</div>

<br />

<div class="white-opacity rounded">
  <h1>Fiches producteur et vin</h1>
  La fiche producteur contient les informations utiles dans sa partie gauche.<br /><br />
  Elle regroupe également les fiches vins de ce producteur dans la partie de droite :
  <ul>
    <li><%= wine_icon @wine %> représente le type de vin, ici un vin blanc.</li>
    <li><%= link_to @wine.name, @wine %> est le nom du vin. Cliquez dessus pour ouvrir la fiche de ce vin.</li>
    <li><%= link_to @wine.area.name, @wine.area %> est l'appellation de ce vin. Cliquez dessus pour avoir plus d'informations sur cette appellation.</li>
    <li>
      Finalement viennent plusieurs icones pour interagir avec ce vin :
      <ul>
        <%=raw action_button_show @wine %> permet de voir la fiche du vin. Vous pouvez également cliquer sur son nom.<br />
        <%=raw action_button_wine_tasting @wine %> permet de voir les dégustations connues pour ce vin.<br />
        <%=raw action_button_add_label @wine %> permet d'ajouter une image (étiquette par exemple).<br />
        <%=raw action_button_taste @wine %> permet d'entrer une fiche dégustation si vous avez goûté ce vin.<br />
        <%=raw action_button_encave @wine %> permt d'ajouter ce vin à la liste de vos bouteilles.
      </ul>
    </li>
  </ul>
  Exemple :
  <%= render :template => 'estates/show' %>
</div>

<br />

<div class="row-fluid">
  <div class="span6">
    <div class="white-opacity rounded" style="height: 200px">
      <h1><%= t("menu.track.my_bottles") %></h1>
      <%= link_to raw('<i class="icon-bottles"></i> ') + t("menu.track.my_bottles"), bottles_path %><br />
      Enregistrez les bouteilles que vous possédez pour vous garder une trace de vos découvertes, en suivre l'évolution, connaître à tout instant votre réserve...<br />
      <br />
      <%= link_to raw('<i class="icon-th"></i> ') + t("menu.track.my_racks"), wine_racks_path %><br />
      Permet de regrouper vos bouteilles dans des casiers pour mieux les retrouver.
    </div>
  </div>
  <div class="span6">
    <div class="white-opacity rounded" style="height: 200px">
      <h1><%= t("menu.track.my_tastings") %></h1>
      <%= link_to raw('<i class="icon-tastings"></i> ') + t("menu.track.my_tastings"), tastings_user_path(current_user) %><br />
      Enregistrez une trace des vins que vous dégustez pour mieux retrouver vos coups de coeur.<br />
      <br />
      <%= link_to raw('<i class="icon-thumbs-up"></i> ') + t("menu.discover.recommmandations"), recommanded_wines_path %><%= link_to raw('<i class="icon-random"></i> ') + t("menu.discover.pairings"), pairings_path, :class => 'pull-right' %><br />
      Vos dégustations permettent également de mieux conseiller vous et les autres utilisateurs.
    </div>
  </div>
</div>

app/views/home/share.html.erb
<% set_meta_tags :title => t("home.index.carousel.t4"),
                 :description => ('1'..'3').map {|i| t('home.index.share.p' + i)}.join(' ') %>

<div class="row-fluid">
  <div class="span4">
    <div class="alert alert-info" style="height: 230px; text-align: justify;">
      <h3><%= t('home.share.p1.title') %></h3>
      <%= t('home.share.p1.text', count: 10*(User.count/10)) %><br /><br />
      <%= image_tag 'why/users.jpg' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-success" style="height: 230px; text-align: justify;">
      <h3><%= t('home.share.p2.title') %></h3>
      <%= t('home.share.p2.text') %><br /><br />
      <%= image_tag 'why/recommandation.jpg' %>
    </div>
  </div>
  <div class="span4">
    <div class="alert alert-info" style="height: 230px; text-align: justify;">
      <h3><%= t('home.share.p3.title') %></h3>
      <ul>
        <% @sheeters.each do |user| %>
          <li><%= user[:name] %> (<%= t('home.share.p3.sheets', count: user[:count]) %>)</li>
        <% end %>
      </ul>
      <ul>
        <% @tasters.each do |user| %>
          <li><%= user[:name] %> (<%= t('home.share.p3.tastings', count: user[:count]) %>)</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/temperature.html.erb
<% set_meta_tags :title => t('temperature.title'),
                 :description => t('temperature.description') %>

<div class="white-opacity rounded">
  <h1><%= t('temperature.title') %></h1>
  
  <div class="row-fluid">
    <div class="span6">
      <%= t('temperature.introduction.introduction') %>
      <ul>
        <li><%= t('temperature.introduction.cold') %></li>
        <li><%= t('temperature.introduction.hot') %></li>
      </ul>
    </div>
    <div class="span6">
      <div class="well"><%= t('temperature.introduction.well') %></div>
    </div>
  </div>
</div>

<br />
  
<div class="row-fluid">
  <div class="span6 white-opacity rounded">
    <h2><%= t('temperature.red.title') %></h2>
    <table class="table table-condensed table-striped">
      <tr><td><%= t('temperature.red.light') %></td><td>12°-14°C</td></tr>
      <tr><td><%= t('temperature.red.middle') %></td><td>14°-16°C</td></tr>
      <tr><td><%= t('temperature.red.strong') %></td><td>16°-18°C</td></tr>
    </table>
    <div class="well"><%=raw t('temperature.red.well1') %></div>
    <div class="well"><%= t('temperature.red.well2') %></div>
  </div>
  <div class="span6 white-opacity rounded">
    <h2><%= t('temperature.white.title') %></h2>
    <table class="table table-condensed table-striped">
      <tr><td><%= t('temperature.white.sparkling') %></td><td>8°-10°C</td></tr>
      <tr><td><%= t('temperature.white.light') %></td><td>8°-10°C</td></tr>
      <tr><td><%= t('temperature.white.gras') %></td><td>10°-12°C</td></tr>
      <tr><td><%= t('temperature.white.sweeter') %></td><td>6°-8°C</td></tr>
      <tr><td><%= t('temperature.white.sweet') %></td><td>8°-10°C</td></tr>
      <tr><td><%= t('temperature.white.jaune') %></td><td>14°-16°C</td></tr>
    </table><br />
    <h2><%= t('temperature.rose.title') %></h2>
    <table class="table table-condensed table-striped">
      <tr><td><%= t('temperature.rose.light') %></td><td>8°-10°C</td></tr>
      <tr><td><%= t('temperature.rose.structured') %></td><td>10°-12°C</td></tr>
    </table>
  </div>
</div>

<br />

app/views/home/track.html.erb
<% set_meta_tags :title => t("home.track.summary.title"),
                 :description => ('1'..'6').map {|i| t('home.track.summary.p' + i + '.title')}.join(' - ') %>

<div class="row-fluid">
  <div class="span12 alert alert-success alert-no-close">
    <h1><%= t('home.track.summary.title')%></h1>
  </div>
</div>

<div class="row-fluid">
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p1.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p1.p1', count: 100*(Wine.validated.count/100)) %><br />
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p1.p2') %>
      </p>
      <%= image_tag('track/p1.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p2.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p2.p1') %><br />
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p2.p2') %>
      </p>
      <%= image_tag('track/p2.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
</div>

<br />

<div class="row-fluid">
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p3.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p3.p1') %><br />
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p3.p2') %>
      </p>
      <%= image_tag('track/p3.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p4.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p4.p1') %><br />
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p4.p2') %>
      </p>
      <%= image_tag('track/p4.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
</div>

<br />

<div class="row-fluid">
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p5.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p5.p1') %>
      </p>
      <%= image_tag('track/p5.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
  <div class="span6 alert alert-success alert-no-close">
    <div style="height: 360px; position: relative">
      <h3><%= raw t('home.track.summary.p6.title') %></h3>
      <p>
        <i class="icon-hand-right"></i><%= raw t('home.track.summary.p6.p1') %>
      </p>
      <%= image_tag('track/p6.jpg', style: 'position: absolute; bottom: 15px;') %>
    </div>
  </div>
</div>